# .travis.yml
language: go

# Only build tags
if: tag IS present

env:
  - DEP_VERSION="0.5.0"

install:
  - go get ./...

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux